# Generated by Django 3.2.25 on 2025-11-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0003_auto_20251115_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
